### ISSUE TITLE
просмотр истории

### ISSUE THREAD

**Issue by IR0NCaT** [vladpen/cams-pwa#1]
После обновления 18-го мая перестал работать просмотр истории

Ошибка:
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

**Comment by vladpen** [comment]
Возможно, в кеше застряла промежуточная версия скрипта. Попробуйте очистить кеш браузера (и проверьте git pull на сервере). Я не могу воспроизвести ни на десктопе, ни на телефонах. Гитхаб с локальной версией синхронизирован.

P.S. 18-го было большое обновление с миграцией на MSE, немного изменилась структура конфига и, самое главное, команда ffmpeg. Требуется изменение локального конфига и перезапуск сервера. Старые (не фрагментированные) сегменты MSE воспроизводить не умеет, да.

**Comment by IR0NCaT** [comment]
Спасибо.  Проблема в старых (не фрагментированных) данных) .  Всё работает.
