### ISSUE TITLE
Не запускается сервер после обновления с BaseServer

### ISSUE THREAD

**Issue by IR0NCaT** [vladpen/cams-pwa#2]
с конфигом по умолчанию ошибки при запуске
в логе ничего нет :(

```
$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import web
  File "/cams-pwa/server/web.py", line 44, in <module>
    class Handler(BaseHTTPRequestHandler):
  File "/cams-pwa/server/web.py", line 45, in Handler
    def __init__(self, request: bytes, client_address: tuple[str, int], server: BaseServer):
TypeError: 'type' object is not subscriptable

```

**Comment by vladpen** [comment]
Сообщите, пожалуйста, вашу версию python. C 3.11 запускается?

**Comment by IR0NCaT** [comment]
> Сообщите, пожалуйста, вашу версию python. C 3.11 запускается?

Python 3.8.10

**Comment by vladpen** [comment]
Исправлено.

Виновата была аннотация типа tuple[str, int]. Старый Python такое не понимает, ему нужно указывать Tuple[str, int] и, соответственно, импортировать "from typing import Tuple". PyCharm подвёл при рефакторинге.

Спасибо за отчёт об ошибке!
