### ISSUE TITLE
Видеофайл отказывается загружаться в браузер

### ISSUE THREAD

**Issue by Eldamorh** [vladpen/cams-pwa#3]
При попытке открыть любую камеру выдает в js-е `player.js:46 Failed to load because no supported source was found.`. 
Предполагаю что проблема в ssl, но не могу найти где то конкретно меня отбивает. Выводя live_url и попытке перейти по нему выдает `Not allowed to load local resource: blob:http://remote_ip:8000/14467f98-f79d-4a44-a69d-8f6c2934136c`
В рамках моей среды, локально развернуть проект я не могу, так же не охота подписывать сертфикат letsencrypt-ом(придется найти домен).
Меня так же отбивало и в попытках логина, но там я просто убрал header Secure. Что делать с текущей проблемой мало представления.

**Comment by vladpen** [comment]
Нет, проблема не в сертификате. SSL даёт дополнительные плюшки для PWA + безопасную авторизацию, но работать будет и по HTTP.

mp4 в кодировке Н.264 должен крутиться вообще везде. Вы случайно кодек не забыли указать в поле codecs в конфиге?

Это такое требование интерфейса MSE. Например, для моих камер я использую avc1.42001f для h.264 и hev1.1.6.L120.0 для h.265.

**Comment by Eldamorh** [comment]
В файле конфига для камеры я указал кодек avc1.42001f, сама камера отдает H264 поток. 
Сами видеофайлы коректно записываются на сервер, я их спокойно достаю ручками через SFTP.

Нужно ли как то отдельно настраивать обслуживание медиа файлов может? 
Сейчас я просто запускаю сервер в открытую на удаленной машине и конекчусь со своей стороны

**Comment by vladpen** [comment]
Нет, настраивать там нечего.
Я бы сначала проверил, пишутся ли видеосегменты (для MSE нужны именно сегменты, простой фрагментации  mp4 недостаточно). Если файлы создаются, скачать один и попробовать воспроизвести в браузере напрямую.

**Comment by Eldamorh** [comment]
Скаченные видеофайлы без проблем открываются в VLC, но не открываются в браузере(есть только звук). 
Легким костылем, как я понял, можно использовать storage command-у в конфиге и просто перекодировать видео для совместимости. Или же есть какое то более оптимальное решение?

**Comment by vladpen** [comment]
Конечно, перекодировать можно, без проблем. Но это вызовет дополнительную нагрузку на сервер.

У VLC свой программный транскодер на стороне пользователя, поэтому там всё работает. Приложение сams-PWA эксплуатирует возможность браузеров на основе chromium воспроизводить видео с помощью аппаратного декодирования. Это выгодно и на сервере, и на клиенте, особенно на смартфонах и если камер несколько (сильно экономит аккумулятор).

Может, у вас на устройстве нет аппаратного ускорения или оно отключено в браузере? Какой у вас браузер, на какой операционной системе и что за устройство?

**Comment by Eldamorh** [comment]
Браузер: Google Chrome, плашка "Use graphics acceleration" включена
ОС : Windows 10 
CPU: Intel Core i5-4590, со встройкой HD Graphics 4600

Если вам так будет удобно, могли бы перейти в телеграм
@crazybobos

**Comment by vladpen** [comment]
В файле README.md добавлен раздел "Возможные проблемы".
